#include "aa_overlay.h"

#include <stdio.h>
#include <string.h>

#include "dev_settings.h"
#include "lvgl.h"
#include "vesc_battery_calc.h"
#include "vesc_can/vesc_lisp_poll.h"
#include "vesc_can/vesc_rt_data.h"
#include "vesc_can/vesc_datatypes.h"

/* Panel-native (portrait) dimensions, mirrored from display_video.c. The
 * AA frame in `fb` was rotated 90° CW into this layout, so the user sees
 * USER_W × USER_H landscape. */
#define PANEL_W   480
#define PANEL_H   800
#define USER_W    800
#define USER_H    480

/* AA bottom-bar zone we paint into. AA's own stock bar is ~10 % of frame
 * height (~48 px on a 480-tall user image). We hug the bottom and use the
 * free gaps the AA bar leaves between the mic/app cluster and the clock.
 *
 * Anchors chosen empirically against the stock AA layout (Pixel, AA 11):
 *   left zone  ≈ x 110..290 (between mic & Maps icon)
 *   right zone ≈ x 510..720 (between settings & clock)
 * Slight breathing room from the icons keeps widgets readable even when
 * AA tweaks bar spacing by a few px. */
#define BAR_BOTTOM_PAD  3
#define SPEED_LEFT_X    150
#define BATT_RIGHT_X    678

#define COLOR_TEXT      0xFFFFu     /* RGB565 white */
#define COLOR_OUTLINE   0x0000u     /* RGB565 black halo — keeps text legible
                                       even if AA shifts its bar around or
                                       shows a brighter app there */
#define COLOR_BATT_OK   0x4FE8u     /* RGB565 lime — matches AA accent green */
#define COLOR_BATT_MID  0xFD20u     /* amber, 20-50 % */
#define COLOR_BATT_LOW  0xF800u     /* red, <20 % */
#define GLOBAL_ALPHA    230u

extern const lv_font_t lv_font_Antonio_Regular_64;  /* big digits */
extern const lv_font_t lv_font_Antonio_Regular_22;  /* small unit label */

/* Cruise-control icon (38×38, LV_IMG_CF_TRUE_COLOR_ALPHA). Generated by
 * GUI Guider under Super_VESC_Display/generated/images/. We reuse the same
 * asset the LVGL dashboard uses so the cockpit and AA overlay show an
 * identical glyph. */
LV_IMG_DECLARE(_cruise_control_alpha_38x38);

/* 4-bpp anti-aliased opacity table — same numbers LVGL uses internally
 * (lv_draw_sw_letter.c::_lv_bpp4_opa_table). */
static const uint8_t bpp4_opa[16] = {
      0, 17, 34, 51, 68, 85, 102, 119,
    136, 153, 170, 187, 204, 221, 238, 255
};

static inline void blend_user_pixel(uint16_t *fb, int ux, int uy,
                                    uint16_t color, uint8_t alpha)
{
    if (alpha == 0) return;
    if ((unsigned)ux >= USER_W || (unsigned)uy >= USER_H) return;
    /* User landscape (ux, uy) → panel-native (px, py) for ROTATE_90 CW.
     * Same mapping touch_input.c uses: px = (USER_H-1) - uy, py = ux. */
    int px = (USER_H - 1) - uy;
    int py = ux;
    int idx = py * PANEL_W + px;
    if (alpha == 255) { fb[idx] = color; return; }

    uint16_t bg = fb[idx];
    int r1 = (color >> 11) & 0x1F;
    int g1 = (color >> 5)  & 0x3F;
    int b1 =  color        & 0x1F;
    int r2 = (bg    >> 11) & 0x1F;
    int g2 = (bg    >> 5)  & 0x3F;
    int b2 =  bg           & 0x1F;
    int r = (r1 * alpha + r2 * (255 - alpha)) / 255;
    int g = (g1 * alpha + g2 * (255 - alpha)) / 255;
    int b = (b1 * alpha + b2 * (255 - alpha)) / 255;
    fb[idx] = (r << 11) | (g << 5) | b;
}

static void fill_user_rect(uint16_t *fb, int x, int y, int w, int h,
                           uint16_t color, uint8_t alpha)
{
    for (int dy = 0; dy < h; dy++) {
        for (int dx = 0; dx < w; dx++) {
            blend_user_pixel(fb, x + dx, y + dy, color, alpha);
        }
    }
}

/* Render one glyph at (pen_x, line_top_y); return the advance width. */
static uint16_t draw_glyph(uint16_t *fb, const lv_font_t *font, uint32_t letter,
                           int pen_x, int line_top_y,
                           uint16_t color, uint8_t global_alpha)
{
    lv_font_glyph_dsc_t g;
    if (!lv_font_get_glyph_dsc(font, &g, letter, 0)) return 0;
    if (g.box_w == 0 || g.box_h == 0) return g.adv_w;
    const uint8_t *bm = lv_font_get_glyph_bitmap(font, letter);
    if (!bm) return g.adv_w;

    int ascent = font->line_height - font->base_line;
    int gy0 = line_top_y + ascent - g.box_h - g.ofs_y;
    int gx0 = pen_x + g.ofs_x;
    int bpp = g.bpp;

    for (int row = 0; row < g.box_h; row++) {
        for (int col = 0; col < g.box_w; col++) {
            int bit_ofs = (row * g.box_w + col) * bpp;
            int byte_idx = bit_ofs >> 3;
            int bit_in_byte = bit_ofs & 7;
            uint8_t a = 0;
            switch (bpp) {
            case 4:
                a = bpp4_opa[(bm[byte_idx] >> (4 - bit_in_byte)) & 0x0F];
                break;
            case 8:
                a = bm[byte_idx];
                break;
            case 2:
                a = (uint8_t)(((bm[byte_idx] >> (6 - bit_in_byte)) & 0x03) * 85);
                break;
            case 1:
                a = ((bm[byte_idx] >> (7 - bit_in_byte)) & 0x01) ? 255 : 0;
                break;
            default:
                continue;
            }
            if (a == 0) continue;
            uint8_t eff = (uint16_t)a * global_alpha / 255;
            blend_user_pixel(fb, gx0 + col, gy0 + row, color, eff);
        }
    }
    return g.adv_w;
}

static int measure_text(const lv_font_t *font, const char *s)
{
    int w = 0;
    while (*s) {
        lv_font_glyph_dsc_t g;
        if (lv_font_get_glyph_dsc(font, &g, (unsigned char)*s++, 0)) {
            w += g.adv_w;
        }
    }
    return w;
}

/* line_top placement for a given font so that its baseline lands on
 * baseline_y (shared across fonts of different sizes). */
static inline int line_top_for_baseline(const lv_font_t *f, int baseline_y)
{
    int ascent = f->line_height - f->base_line;
    return baseline_y - ascent;
}

static int draw_text(uint16_t *fb, const lv_font_t *font,
                     int pen_x, int line_top_y, const char *s,
                     uint16_t color, uint8_t alpha)
{
    int x0 = pen_x;
    while (*s) {
        pen_x += draw_glyph(fb, font, (unsigned char)*s++, pen_x, line_top_y,
                            color, alpha);
    }
    return pen_x - x0;
}

/* White text + a 1-px black halo (N/S/E/W). 4 outline passes is enough to
 * keep light digits readable against any video background; a full 8-way
 * outline would be twice the cost for diagonal pixels barely visible at
 * this font size. */
static int draw_text_with_halo(uint16_t *fb, const lv_font_t *font,
                               int pen_x, int line_top_y, const char *s)
{
    draw_text(fb, font, pen_x - 1, line_top_y,     s, COLOR_OUTLINE, GLOBAL_ALPHA);
    draw_text(fb, font, pen_x + 1, line_top_y,     s, COLOR_OUTLINE, GLOBAL_ALPHA);
    draw_text(fb, font, pen_x,     line_top_y - 1, s, COLOR_OUTLINE, GLOBAL_ALPHA);
    draw_text(fb, font, pen_x,     line_top_y + 1, s, COLOR_OUTLINE, GLOBAL_ALPHA);
    return draw_text(fb, font, pen_x, line_top_y, s, COLOR_TEXT, GLOBAL_ALPHA);
}

/* Stamp an LV_IMG_CF_TRUE_COLOR_ALPHA image (LV_COLOR_DEPTH=16 layout:
 * 3 bytes per pixel — color_lo, color_hi, alpha) as a single-color mask.
 * The image's own RGB is discarded; only the alpha channel drives the blend.
 * That keeps the asset reusable across themes — same bitmap, any tint. */
static void draw_alpha_image_tinted(uint16_t *fb, const lv_img_dsc_t *img,
                                    int x, int y,
                                    uint16_t color, uint8_t global_alpha)
{
    if (!img || !img->data) return;
    int w = img->header.w;
    int h = img->header.h;
    const uint8_t *p = img->data;
    for (int row = 0; row < h; row++) {
        for (int col = 0; col < w; col++) {
            uint8_t a = p[2];           /* skip color, take alpha */
            p += 3;
            if (a == 0) continue;
            uint8_t eff = (uint16_t)a * global_alpha / 255;
            blend_user_pixel(fb, x + col, y + row, color, eff);
        }
    }
}

/* Tinted alpha image + 1-px black halo (N/S/E/W) for legibility on top of
 * arbitrary video. Mirrors the technique draw_text_with_halo uses for text. */
static void draw_alpha_image_with_halo(uint16_t *fb, const lv_img_dsc_t *img,
                                       int x, int y, uint16_t color)
{
    draw_alpha_image_tinted(fb, img, x - 1, y,     COLOR_OUTLINE, GLOBAL_ALPHA);
    draw_alpha_image_tinted(fb, img, x + 1, y,     COLOR_OUTLINE, GLOBAL_ALPHA);
    draw_alpha_image_tinted(fb, img, x,     y - 1, COLOR_OUTLINE, GLOBAL_ALPHA);
    draw_alpha_image_tinted(fb, img, x,     y + 1, COLOR_OUTLINE, GLOBAL_ALPHA);
    draw_alpha_image_tinted(fb, img, x,     y,     color,         GLOBAL_ALPHA);
}

/* Battery glyph: rounded body + small tip on the right, level fill scales
 * with `pct` (0..100). Drawn in user-landscape coords, top-left anchor.
 * Body is BATT_W × BATT_H, tip BATT_TIP_W × BATT_TIP_H centered vertically. */
#define BATT_W      28
#define BATT_H      14
#define BATT_TIP_W  3
#define BATT_TIP_H  6

static void draw_battery_icon(uint16_t *fb, int x, int y, int pct)
{
    uint16_t fill = (pct <= 20) ? COLOR_BATT_LOW
                  : (pct < 50)  ? COLOR_BATT_MID
                  : COLOR_BATT_OK;
    if (pct < 0) pct = 0;
    if (pct > 100) pct = 100;

    /* Halo: 1-px black ring around the icon so it pops on any background. */
    fill_user_rect(fb, x - 1, y - 1, BATT_W + BATT_TIP_W + 2, BATT_H + 2,
                   COLOR_OUTLINE, GLOBAL_ALPHA);

    /* Body outline (white, 1px). */
    fill_user_rect(fb, x, y, BATT_W, BATT_H, COLOR_TEXT, GLOBAL_ALPHA);

    /* Inner cut-out (dark) — keeps fill level readable. */
    fill_user_rect(fb, x + 2, y + 2, BATT_W - 4, BATT_H - 4,
                   COLOR_OUTLINE, GLOBAL_ALPHA);

    /* Fill from the left, proportional to pct. */
    int fill_w = (BATT_W - 4) * pct / 100;
    if (fill_w > 0) {
        fill_user_rect(fb, x + 2, y + 2, fill_w, BATT_H - 4, fill, GLOBAL_ALPHA);
    }

    /* Tip on the right, vertically centered. */
    int tip_y = y + (BATT_H - BATT_TIP_H) / 2;
    fill_user_rect(fb, x + BATT_W, tip_y, BATT_TIP_W, BATT_TIP_H,
                   COLOR_TEXT, GLOBAL_ALPHA);
}

void aa_overlay_draw(uint16_t *fb)
{
    if (!fb) return;

    /* Read VESC RT data directly. The cockpit_get_*() cache used to feed
     * this overlay is updated from an lv_timer, which freezes whenever the
     * AA path pauses the LVGL worker (esp_lv_adapter_pause in display_video).
     * vesc_rt_data has its own FreeRTOS poller and stays live regardless,
     * so it's the only source guaranteed to be fresh while AA video runs. */
    unsigned speed = 0;
    unsigned batt  = 0;
    bool cc_active = false;
    if (vesc_rt_data_is_fresh()) {
        const vesc_setup_values_t *rt = vesc_rt_data_get_latest();
        float spd_kmh = vesc_rt_data_get_speed_kmh();
        if (spd_kmh < 0) spd_kmh = -spd_kmh;
        int s = (int)(spd_kmh + 0.5f);
        speed = s < 0 ? 0u : (s > 999 ? 999u : (unsigned)s);

        /* Battery percent — Smart mode delegates to the persistent tracker
         * so the HUD agrees with the VESC dashboard; Direct mode uses the
         * controller's voltage-based estimate. */
        float pct;
        if (settings_get_battery_calc_mode() == BATTERY_CALC_MODE_SMART) {
            pct = battery_calc_get_smart_percentage(
                    rt->battery_level, rt->amp_hours,
                    settings_get_battery_capacity());
        } else {
            pct = rt->battery_level * 100.0f;
        }
        int b = (int)(pct + 0.5f);
        batt = b < 0 ? 0u : (b > 99 ? 99u : (unsigned)b);
    }
    /* Cruise indicator — independent of vesc_rt_data freshness; Lisp poll
     * has its own pump and may report CC active even if the RT poll just
     * gapped a frame. */
    int32_t cc_val = 0;
    if (vesc_lisp_poll_get_variable_int("cruise-active", &cc_val)) {
        cc_active = (cc_val != 0);
    }

    char speed_buf[8];
    char batt_buf[8];
    snprintf(speed_buf, sizeof speed_buf, "%u", speed);
    snprintf(batt_buf,  sizeof batt_buf,  "%u", batt);

    const lv_font_t *big = &lv_font_Antonio_Regular_64;
    const lv_font_t *sml = &lv_font_Antonio_Regular_22;

    /* Shared baseline at BAR_BOTTOM_PAD px above the frame bottom. Both
     * fonts hang their glyphs from this baseline so digits and unit labels
     * sit on the same line regardless of size. */
    int baseline_y = USER_H - BAR_BOTTOM_PAD;
    int big_top = line_top_for_baseline(big, baseline_y);
    int sml_top = line_top_for_baseline(sml, baseline_y);

    /* ── Speed widget (left) ──
     * "64" in big, " KM/H" in small, anchored to SPEED_LEFT_X.
     * When cruise control is engaged, the cruise icon lights up in the gap
     * to the LEFT of SPEED_LEFT_X. Position is fixed — speed digits stay
     * anchored to SPEED_LEFT_X regardless of CC state, so engaging cruise
     * doesn't shift the readout left/right. */
    int x = SPEED_LEFT_X;
    if (cc_active) {
        const lv_img_dsc_t *cc_img = &_cruise_control_alpha_38x38;
        int icon_w = cc_img->header.w;
        int icon_h = cc_img->header.h;
        int icon_x = SPEED_LEFT_X - icon_w - 6;
        int icon_y = baseline_y - icon_h - 2;
        draw_alpha_image_with_halo(fb, cc_img, icon_x, icon_y, COLOR_BATT_OK);
    }
    x += draw_text_with_halo(fb, big, x, big_top, speed_buf);
    x += 4;
    draw_text_with_halo(fb, sml, x, sml_top, "KM/H");

    /* ── Battery widget (right) ──
     * [icon] [gap] "78" big "%" small, right-anchored at BATT_RIGHT_X. */
    int batt_digits_w = measure_text(big, batt_buf);
    int pct_w         = measure_text(sml, "%");
    int icon_total_w  = BATT_W + BATT_TIP_W;
    int icon_gap      = 6;
    int total_w = icon_total_w + icon_gap + batt_digits_w + 1 + pct_w;

    int x0 = BATT_RIGHT_X - total_w;
    int icon_y = baseline_y - (big->line_height - big->base_line) +
                 ((big->line_height - big->base_line) - BATT_H) / 2;
    draw_battery_icon(fb, x0, icon_y, batt);
    int xt = x0 + icon_total_w + icon_gap;
    xt += draw_text_with_halo(fb, big, xt, big_top, batt_buf);
    xt += 1;
    draw_text_with_halo(fb, sml, xt, sml_top, "%");
}
