/// Owns the downloaded map data: the routing graph, the search index and the
/// tile cache.
///
/// The data is generated by scripts/mapgen and served over plain HTTP — during
/// development that is `python3 -m http.server` inside `vtiles/`. Files land in
/// the app's support directory (not the cache directory, which the OS is free
/// to purge) and are loaded in an isolate, because parsing 17 MB takes long
/// enough to drop frames.
///
/// Messages surface as i18n keys plus arguments rather than English text, the
/// same convention as firmware/firmware_updater.dart, so the UI localises them.
library;

import 'dart:async';
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:package_info_plus/package_info_plus.dart';
import 'package:path_provider/path_provider.dart';

import 'rgf2.dart';
import 'router.dart';
import 'search_index.dart';
import 'tile_cache.dart';

enum MapDataState { absent, downloading, loading, ready, error }

class MapData extends ChangeNotifier {
  MapData._();
  static final MapData instance = MapData._();

  static const graphFileName = 'route_graph.bin';
  static const indexFileName = 'search_index.tsv';

  Directory? _dir;
  MapDataState _state = MapDataState.absent;
  double _progress = 0;
  String? _progressFile;
  String? _messageKey;
  Map<String, String>? _messageArgs;

  RouteGraph? _graph;
  SearchIndex? _index;
  Router? _router;
  TileCache? _tiles;
  String _userAgent = 'AaBridgeNavigator/dev';

  MapDataState get state => _state;
  double get progress => _progress;
  String? get progressFile => _progressFile;
  String? get messageKey => _messageKey;
  Map<String, String>? get messageArgs => _messageArgs;
  RouteGraph? get graph => _graph;
  SearchIndex? get index => _index;
  Router? get router => _router;
  TileCache? get tiles => _tiles;
  String get userAgent => _userAgent;
  bool get isReady => _state == MapDataState.ready && _router != null;

  File? get graphFile =>
      _dir == null ? null : File('${_dir!.path}/$graphFileName');
  File? get indexFile =>
      _dir == null ? null : File('${_dir!.path}/$indexFileName');

  /// Resolves storage, builds the User-Agent and loads whatever is already
  /// downloaded. Safe to call without awaiting — the UI listens instead.
  Future<void> init() async {
    if (_dir != null) return;
    final support = await getApplicationSupportDirectory();
    _dir = Directory('${support.path}/nav');
    await _dir!.create(recursive: true);
    try {
      final info = await PackageInfo.fromPlatform();
      _userAgent = 'AaBridgeNavigator/${info.version} '
          '(+https://github.com/payalneg/esp32p4-android-auto)';
    } on Object {
      // Not fatal: a generic-looking UA is worse than a versioned one, but
      // failing to start the navigator over it would be sillier.
    }
    _tiles = TileCache(Directory('${support.path}/tiles/osm'),
        userAgent: _userAgent);
    await _loadFromDisk();
  }

  Future<void> _loadFromDisk() async {
    final g = graphFile;
    if (g == null || !await g.exists()) {
      _set(MapDataState.absent);
      return;
    }
    _set(MapDataState.loading);
    try {
      _graph = await RouteGraph.load(g.path);
      _router = Router(_graph!);
      final idx = indexFile;
      _index = (idx != null && await idx.exists())
          ? await SearchIndex.load(idx.path)
          : null;
      _set(MapDataState.ready);
    } on FormatException catch (e) {
      _graph = null;
      _router = null;
      _fail('mapdata.err.badGraph', <String, String>{'err': e.message});
    } on Object catch (e) {
      _graph = null;
      _router = null;
      _fail('mapdata.err.load', <String, String>{'err': '$e'});
    }
  }

  /// Downloads both files from [baseUrl] and loads them.
  Future<void> downloadFrom(String baseUrl) async {
    await init();
    final base = baseUrl.trim();
    if (base.isEmpty) {
      _fail('mapdata.err.noUrl', null);
      return;
    }
    final root = Uri.tryParse(base.endsWith('/') ? base : '$base/');
    if (root == null || !root.hasScheme) {
      _fail('mapdata.err.badUrl', <String, String>{'url': base});
      return;
    }
    _messageKey = null;
    _messageArgs = null;
    _set(MapDataState.downloading);
    final client = HttpClient()..userAgent = _userAgent;
    try {
      await _download(client, root.resolve(graphFileName), graphFile!);
      // The index is optional: routing works without search.
      try {
        await _download(client, root.resolve(indexFileName), indexFile!);
      } on Object {
        final stale = indexFile;
        if (stale != null && await stale.exists()) await stale.delete();
      }
      await _loadFromDisk();
    } on _HttpStatusException catch (e) {
      _fail('mapdata.err.http', <String, String>{'code': '${e.statusCode}'});
    } on Object catch (e) {
      _fail('mapdata.err.download', <String, String>{'err': '$e'});
    } finally {
      client.close(force: true);
    }
  }

  Future<void> _download(HttpClient client, Uri url, File dest) async {
    _progressFile = url.pathSegments.last;
    _progress = 0;
    notifyListeners();
    final resp = await (await client.getUrl(url)).close();
    if (resp.statusCode != 200) {
      await resp.drain<void>();
      throw _HttpStatusException(resp.statusCode);
    }
    final total = resp.contentLength;
    // Write to .part first: a half-downloaded graph that looks complete would
    // fail its magic check on every launch afterwards.
    final part = File('${dest.path}.part');
    final sink = part.openWrite();
    var received = 0;
    try {
      await for (final chunk in resp) {
        sink.add(chunk);
        received += chunk.length;
        if (total > 0) {
          final p = received / total;
          if (p - _progress > 0.01) {
            _progress = p;
            notifyListeners();
          }
        }
      }
      await sink.flush();
    } finally {
      await sink.close();
    }
    await part.rename(dest.path);
  }

  /// Copies a file the user picked into place and loads it.
  Future<void> importGraph(String srcPath) => _import(srcPath, graphFile!);
  Future<void> importIndex(String srcPath) => _import(srcPath, indexFile!);

  Future<void> _import(String srcPath, File dest) async {
    await init();
    _set(MapDataState.loading);
    try {
      await File(srcPath).copy(dest.path);
      await _loadFromDisk();
    } on Object catch (e) {
      _fail('mapdata.err.import', <String, String>{'err': '$e'});
    }
  }

  Future<void> deleteAll() async {
    await init();
    for (final f in <File?>[graphFile, indexFile]) {
      if (f != null && await f.exists()) await f.delete();
    }
    _graph = null;
    _index = null;
    _router = null;
    _set(MapDataState.absent);
  }

  void _set(MapDataState s) {
    _state = s;
    if (s != MapDataState.error) {
      _messageKey = null;
      _messageArgs = null;
    }
    if (s != MapDataState.downloading) {
      _progress = 0;
      _progressFile = null;
    }
    notifyListeners();
  }

  void _fail(String key, Map<String, String>? args) {
    _messageKey = key;
    _messageArgs = args;
    _state = MapDataState.error;
    _progress = 0;
    _progressFile = null;
    notifyListeners();
  }
}

class _HttpStatusException implements Exception {
  _HttpStatusException(this.statusCode);
  final int statusCode;
}
