#!/usr/bin/env python3
"""
Rewrites the `dashboard` screen in Super_VESC_Display.guiguider so it matches
the Cockpit design from `payalne vesc dashboard/lvgl/SPEC.md`.

Source of truth for the layout: payalne vesc dashboard/lvgl/cockpit-standalone.html.
Idempotent: can be re-run any time, the dashboard is rebuilt from scratch and
the rest of the .guiguider file is left untouched.

Usage:
    python3 tools/build_cockpit_guiguider.py
"""

from __future__ import annotations

import copy
import json
import os
import random
import shutil
import string
import sys
from typing import Any

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT = os.path.join(ROOT, "Super_VESC_Display.guiguider")
BACKUP = PROJECT + ".bak"

# Cockpit widgets with these names are renamed to legacy names from .bak so
# the existing custom.c keeps compiling without changes.
RENAME_TO_LEGACY = {
    "speed_value":       "Speed_text",
    "battery_value":     "Battery_proc_text",
    "battery_volt":      "Voltage_text",
    "battery_range_val": "Range_text",
    "power_sub":         "Current_text",
    "col_mtmp_value":    "temp_mot_text",
    "col_ctmp_value":    "temp_esc_text",
    "status_mode":       "mode_text",
    "status_time":       "uptime_text",
    "col_odo_value":     "odo_text",
    "col_trip_value":    "TRIP_text",
}

# These legacy widgets have no semantic place in the Cockpit, but custom.c
# still references them. We pull them from .bak as-is, regenerate ids, and
# keep them invisible.
LEGACY_STUBS_HIDDEN = [
    "Ah_const_text", "Ah_text", "temp_bat_text",
    "ble_connected_img", "cruise_control_img", "esc_not_connected_text",
    "music_text", "navigation_icon", "navigation_text",
    "Speed_meter", "Battery_meter", "Current_meter",
    # fps_text is recreated as a Cockpit widget (see build_cockpit_widgets).
    # The .bak version uses a 24px font and 158x30 box that does not fit the
    # Cockpit status bar.
]
LEGACY_STUBS_VISIBLE: list[str] = []  # all legacy stubs are hidden by default

# ---------------------------------------------------------------------------
# Cockpit palette (1:1 with lvgl/SPEC.md)
# ---------------------------------------------------------------------------
BG_0 = "#07090A"
BG_1 = "#0D1113"
BG_2 = "#161B1E"
LINE = "#1F2629"
LINE_2 = "#2A3236"
TEXT = "#E8EDEE"
TEXT_DIM = "#8A9499"
TEXT_FAINT = "#4A5358"
ACCENT = "#B6FF2E"
WARN = "#FFB02E"
DANGER = "#FF3B30"

# ---------------------------------------------------------------------------
# Fonts available in the project.
#   Antonio_Regular  — sans-serif condensed, closest replacement for Barlow Condensed.
#   montserratMedium — labels and mono-style fallback.
# Sizes that are not yet present (32, 64, 220) will be auto-generated by GUI
# Guider into generated/guider_fonts/ on Generate Code.
# ---------------------------------------------------------------------------
FONT_BIG = "Antonio_Regular"     # large digits (220, 64, 32)
FONT_LBL = "montserratMedium"    # labels and units (11, 9, 12)


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------
def gen_id(used: set[str]) -> str:
    """Unique 8-char id [a-z0-9], same shape as .guiguider uses."""
    alphabet = string.ascii_lowercase + string.digits
    while True:
        v = "".join(random.choice(alphabet) for _ in range(8))
        if v not in used:
            used.add(v)
            return v


def style_text(font: int, color: str, align: str = "LEFT",
               family: str = FONT_LBL, letter_space: int = 0) -> dict:
    """Style for a text widget (transparent background, no border)."""
    return {
        "part": "LV_PART_MAIN",
        "state": "LV_STATE_DEFAULT",
        "disable": False,
        "font": font,
        "font_family": family,
        "bg_color": "#000000",
        "bg_grad_color": "#000000",
        "bg_opa": 0,
        "bg_grad_dir": "LV_GRAD_DIR_NONE",
        "bg_dither_mode": "LV_DITHER_NONE",
        "bg_main_stop": 0,
        "bg_grad_stop": 255,
        "border_side": ["LV_BORDER_SIDE_FULL"],
        "border_width": 0,
        "border_color": "#000000",
        "border_opa": 255,
        "text_color": color,
        "text_align": f"LV_TEXT_ALIGN_{align}",
        "letter_space": letter_space,
        "shadow_color": "#000000",
        "shadow_opa": 255,
        "shadow_width": 0,
        "shadow_spread": 0,
        "shadow_ofs_x": 0,
        "shadow_ofs_y": 0,
        "padding_top": 0,
        "padding_right": 0,
        "padding_bottom": 0,
        "padding_left": 0,
        "radius": 0,
    }


def style_cursor_hidden() -> dict:
    """Transparent cursor for text areas — otherwise LVGL paints a blue bar
    next to the last character by default."""
    return {
        "part": "LV_PART_CURSOR",
        "state": "LV_STATE_DEFAULT",
        "disable": False,
        "bg_color": "#000000",
        "bg_grad_color": "#000000",
        "bg_opa": 0,
        "bg_grad_dir": "LV_GRAD_DIR_NONE",
        "bg_dither_mode": "LV_DITHER_NONE",
        "bg_main_stop": 0,
        "bg_grad_stop": 255,
        "border_side": ["LV_BORDER_SIDE_FULL"],
        "border_width": 0,
        "border_color": "#000000",
        "border_opa": 0,
        "outline_width": 0,
        "outline_opa": 0,
        "shadow_width": 0,
        "shadow_opa": 0,
        "anim_time": 0,
    }


def image(name: str, x: int, y: int, w: int, h: int, img_path: str,
          recolor: str = "#ffffff", recolor_opa: int = 0,
          used: set[str] | None = None) -> dict:
    """Image widget. recolor_opa=255 + recolor=ACCENT tints a grey/white
    asset to the desired colour."""
    return {
        "name": name,
        "id": gen_id(used) if used is not None else gen_id(set()),
        "type": "img",
        "left": x, "top": y, "width": w, "height": h,
        "visible": True,
        "isLock": False,
        "flag": [],
        "default_style": False,
        "use_fs": False,
        "fs_type": "flash",
        "sd_path": "",
        "img_path": img_path,
        "rotate": 0,
        "x": 0,
        "y": 0,
        "color_format": "true-color-alpha",
        "style": [{
            "part": "LV_PART_MAIN",
            "state": "LV_STATE_DEFAULT",
            "disable": False,
            "image_recolor": recolor,
            "image_recolor_opa": recolor_opa,
            "image_opa": 255,
            "radius": 0,
        }],
    }


def style_box(bg: str, radius: int = 0) -> dict:
    """Style for a flat coloured rectangle (segment / divider)."""
    return {
        "part": "LV_PART_MAIN",
        "state": "LV_STATE_DEFAULT",
        "disable": False,
        "font": 16,
        "font_family": FONT_LBL,
        "bg_color": bg,
        "bg_grad_color": bg,
        "bg_opa": 255,
        "bg_grad_dir": "LV_GRAD_DIR_NONE",
        "bg_dither_mode": "LV_DITHER_NONE",
        "bg_main_stop": 0,
        "bg_grad_stop": 255,
        "border_side": ["LV_BORDER_SIDE_FULL"],
        "border_width": 0,
        "border_color": "#000000",
        "border_opa": 0,
        "text_color": "#000000",
        "text_align": "LV_TEXT_ALIGN_LEFT",
        "letter_space": 0,
        "shadow_color": "#000000",
        "shadow_opa": 0,
        "shadow_width": 0,
        "shadow_spread": 0,
        "shadow_ofs_x": 0,
        "shadow_ofs_y": 0,
        "padding_top": 0,
        "padding_right": 0,
        "padding_bottom": 0,
        "padding_left": 0,
        "radius": radius,
    }


def text(name: str, x: int, y: int, w: int, h: int, txt: str,
         font: int, color: str, align: str = "LEFT",
         family: str = FONT_LBL, letter_space: int = 0,
         used: set[str] | None = None) -> dict:
    """Text widget. We use type `ta` (text area) — already supported by the
    project, opens fine in GUI Guider; values are read/written via
    lv_textarea_set_text(), which is enough for a static dashboard."""
    return {
        "name": name,
        "id": gen_id(used) if used is not None else gen_id(set()),
        "type": "ta",
        "left": x, "top": y, "width": w, "height": h,
        "visible": True,
        "isLock": False,
        "flag": [],
        "default_style": False,
        "text": txt,
        "password_mode": False,
        "one_line_mode": True,
        "placeholder": "",
        "accept_characters": "",
        "max_len": 64,
        "password_bullet": "*",
        "style": [style_text(font, color, align, family, letter_space),
                  style_cursor_hidden()],
    }


def box(name: str, x: int, y: int, w: int, h: int, bg: str,
        radius: int = 0, used: set[str] | None = None) -> dict:
    """Rectangle widget (used for bar segments and dividers).
    We use a `ta` with empty text and a solid background — the most reliable
    way to get a flat coloured rectangle in GUI Guider 8.x."""
    return {
        "name": name,
        "id": gen_id(used) if used is not None else gen_id(set()),
        "type": "ta",
        "left": x, "top": y, "width": w, "height": h,
        "visible": True,
        "isLock": False,
        "flag": [],
        "default_style": False,
        "text": "",
        "password_mode": False,
        "one_line_mode": True,
        "placeholder": "",
        "accept_characters": "",
        "max_len": 1,
        "password_bullet": "*",
        "style": [style_box(bg, radius), style_cursor_hidden()],
    }


# ---------------------------------------------------------------------------
# Layout
# ---------------------------------------------------------------------------
def build_cockpit_widgets(used_ids: set[str]) -> list[dict]:
    """Returns a flat list of widgets in painting order (top to bottom)."""
    W: list[dict] = []
    add = W.append
    u = used_ids

    # ---- Status bar (y=0..32) -------------------------------------------
    # Bottom divider
    add(box("statusbar_sep", 0, 32, 800, 1, LINE, used=u))

    # Left side: VESC · MODE · TIME
    add(text("status_vesc",  16, 10, 50, 14, "VESC",      11, ACCENT,   "LEFT", letter_space=2, used=u))
    add(text("status_mode",  76, 10, 80, 14, "SPORT",     11, TEXT_DIM, "LEFT", used=u))
    add(text("status_time", 170, 10, 80, 14, "00:42:18",  11, TEXT_DIM, "LEFT", used=u))

    # Right side: BT · GPS · TEMP (anchored to right edge 784)
    add(text("status_temp", 720, 10, 64, 14, "48°C", 11, TEXT_DIM, "RIGHT", used=u))
    add(text("status_gps",  670, 10, 36, 14, "GPS",  11, TEXT_DIM, "RIGHT", used=u))
    # status_bt — "BT" text; colour is toggled by update_ble_status() in custom.c.
    add(text("status_bt",   616, 10, 40, 14, "BT",   11, ACCENT,   "RIGHT", used=u))

    # ---- Battery panel (x=0..180, y=32..400) ----------------------------
    add(box("battery_sep", 180, 32, 1, 368, LINE, used=u))   # right border
    add(text("battery_label", 20, 56, 80, 14, "BATTERY", 11, TEXT_DIM, "LEFT", letter_space=3, used=u))
    # "68" in Antonio@64 LEFT-aligned takes ~75px — % sits right after it.
    add(text("battery_value", 20, 70, 90, 70, "68",      64, ACCENT,   "LEFT", family=FONT_BIG, used=u))
    add(text("battery_pct",   88, 96, 40, 24, "%",       22, TEXT_DIM, "LEFT", used=u))
    add(text("battery_volt",  20,148, 130, 14, "54.2 V", 11, TEXT_DIM, "LEFT", used=u))

    # 14 segments of the battery bar. Step 15 (12 height + 3 gap).
    # Topmost segment y=180, bottommost y=180+13*15=375.
    for i in range(14):
        add(box(f"batt_seg_{i:02d}", 20, 180 + i * 15, 144, 12, BG_2, radius=1, used=u))

    # y=387 sits between the bottom of the last segment (i=13: y=180+13*15=375,
    # bottom 387) and the top of bottom_bg (y=400). Height 12 fits a 11px font.
    add(text("battery_range_label", 20, 387, 60, 12, "RANGE", 11, TEXT_DIM, "LEFT", used=u))
    add(text("battery_range_val",   80, 387, 84, 12, "38 KM", 11, TEXT,     "RIGHT", used=u))

    # ---- Speed panel (x=180..620, y=32..400) ----------------------------
    add(text("speed_label", 180, 42, 440, 14, "SPEED · KM/H", 12, TEXT_DIM, "CENTER", letter_space=4, used=u))
    add(text("speed_value", 180, 60, 440, 240, "32", 220, TEXT, "CENTER", family=FONT_BIG, used=u))

    # 12 segments of the horizontal speed bar; each 24 wide, 2 gap.
    # Total width = 12*24 + 11*2 = 310 px. Centre = 400.
    bar_x0 = 400 - 310 // 2  # = 245
    for i in range(12):
        add(box(f"speed_seg_{i:02d}", bar_x0 + i * 26, 320, 24, 6, BG_2, radius=1, used=u))

    add(text("speed_min", 240, 332,  20, 10, "0",      9, TEXT_FAINT, "LEFT",  used=u))
    add(text("speed_max", 540, 332, 70, 10, "MAX 60",  9, TEXT_FAINT, "RIGHT", used=u))

    # ---- Power panel (x=620..800, y=32..400) ----------------------------
    add(box("power_sep", 620, 32, 1, 368, LINE, used=u))
    add(text("power_label", 636, 56, 144, 14, "POWER", 11, TEXT_DIM, "RIGHT", letter_space=3, used=u))
    # "1.00" in Antonio@64 RIGHT-aligned in [636..724] leaves a visual gap on
    # the right because of TextArea padding — pull kW closer to the digits.
    add(text("power_value", 612, 70, 112, 70, "1.00",  64, ACCENT,   "RIGHT", family=FONT_BIG, used=u))
    add(text("power_unit",  724, 96,  60, 24, "kW",    22, TEXT_DIM, "LEFT",  used=u))
    add(text("power_sub",   636,148, 144, 14, "18.4 A · 2840 RPM", 11, TEXT_DIM, "RIGHT", used=u))

    for i in range(14):
        add(box(f"power_seg_{i:02d}", 636, 180 + i * 15, 144, 12, BG_2, radius=1, used=u))

    add(text("power_max_label", 636, 387, 60, 12, "MAX",    11, TEXT_DIM, "LEFT",  used=u))
    add(text("power_max_val",   696, 387, 84, 12, "4.5 KW", 11, TEXT,     "RIGHT", used=u))

    # ---- Bottom strip (y=400..480, h=80) --------------------------------
    add(box("bottom_bg",  0, 400, 800, 80, BG_1, used=u))
    add(box("bottom_top_sep", 0, 400, 800, 1, LINE, used=u))
    # 4 vertical dividers between the 5 columns
    for i, x in enumerate((160, 320, 480, 640)):
        add(box(f"bottom_col_sep_{i}", x, 400, 1, 80, LINE, used=u))

    columns = [
        ("trip", "TRIP",    "14.2", "KM"),
        ("odo",  "ODO",     "4128", "KM"),
        ("mtmp", "M·TEMP",  "62",   "°C"),
        ("ctmp", "C·TEMP",  "48",   "°C"),
        ("avg",  "AVG",     "24",   "KM/H"),
    ]
    for i, (key, lbl, val, unit) in enumerate(columns):
        col_x = i * 160
        add(text(f"col_{key}_label", col_x, 414, 160, 12, lbl, 11, TEXT_DIM, "CENTER", letter_space=2, used=u))
        # Value RIGHT-aligned to centre, unit LEFT-aligned right after — looks like "32 KM".
        add(text(f"col_{key}_value", col_x,      430, 100, 36, val, 32, TEXT,     "RIGHT", family=FONT_BIG, used=u))
        add(text(f"col_{key}_unit",  col_x + 104, 442,  56, 14, unit, 11, TEXT_DIM, "LEFT",  used=u))

    # fps_text — debug counter, custom.c controls visibility itself. Place it
    # in the top-right of the status bar, hidden, with a 9px font so it does
    # not collide with other text.
    fps = text("fps_text", 480, 10, 130, 14, "FPS", 9, TEXT_FAINT, "RIGHT", used=u)
    fps["visible"] = False
    add(fps)

    # Rename selected Cockpit widgets to legacy names for custom.c compatibility.
    for w in W:
        new_name = RENAME_TO_LEGACY.get(w["name"])
        if new_name:
            w["name"] = new_name
    return W


# ---------------------------------------------------------------------------
# Legacy stubs from .bak
# ---------------------------------------------------------------------------
def regen_ids(node: Any, used: set[str]) -> None:
    """Recursively reassigns every `id` field in the tree to avoid clashes."""
    if isinstance(node, dict):
        if isinstance(node.get("id"), str):
            node["id"] = gen_id(used)
        for v in node.values():
            regen_ids(v, used)
    elif isinstance(node, list):
        for x in node:
            regen_ids(x, used)


def fetch_legacy_stub(bak_dashboard: dict, name: str) -> dict | None:
    """Pulls a widget from the .bak dashboard by name (recursive — meters
    were nested inside tileview/tile)."""
    found: list[dict] = []
    def walk(node: Any) -> None:
        if isinstance(node, dict):
            if node.get("name") == name and node.get("type"):
                found.append(node)
            for v in node.values():
                walk(v)
        elif isinstance(node, list):
            for x in node:
                walk(x)
    walk(bak_dashboard)
    return copy.deepcopy(found[0]) if found else None


def build_legacy_stubs(bak_path: str, used_ids: set[str]) -> list[dict]:
    if not os.path.isfile(bak_path):
        print(f"[warn] {bak_path} missing — skipping legacy stubs", file=sys.stderr)
        return []
    with open(bak_path, "r", encoding="utf-8") as f:
        bak = json.load(f)
    bak_dash = next((s for s in bak.get("FrontJson", []) if s.get("name") == "dashboard"), None)
    if bak_dash is None:
        print("[warn] no dashboard in .bak", file=sys.stderr)
        return []

    out: list[dict] = []
    for name in LEGACY_STUBS_HIDDEN + LEGACY_STUBS_VISIBLE:
        w = fetch_legacy_stub(bak_dash, name)
        if w is None:
            print(f"[warn] {name} not found in .bak", file=sys.stderr)
            continue
        regen_ids(w, used_ids)
        if name in LEGACY_STUBS_HIDDEN:
            w["visible"] = False
            # Stubs sit directly on the screen now (we dropped tileview).
            # Their old coordinates are kept as-is; an invisible widget is
            # not painted anyway.
        else:
            # Visible stubs: parent is now the screen, not a settings_button overlay.
            pass
        out.append(w)
    return out


# ---------------------------------------------------------------------------
# entry point
# ---------------------------------------------------------------------------

def main() -> int:
    if not os.path.isfile(PROJECT):
        print(f"[err] {PROJECT} not found", file=sys.stderr)
        return 1

    if not os.path.isfile(BACKUP):
        shutil.copy2(PROJECT, BACKUP)
        print(f"[i] backup -> {BACKUP}")
    else:
        print(f"[i] backup already exists: {BACKUP}")

    with open(PROJECT, "r", encoding="utf-8") as f:
        proj = json.load(f)

    # FrontJson[0] is the dashboard screen; collect all in-use ids to avoid clashes.
    used_ids: set[str] = set()

    def collect(node: Any) -> None:
        if isinstance(node, dict):
            v = node.get("id")
            if isinstance(v, str) and v:
                used_ids.add(v)
            for vv in node.values():
                collect(vv)
        elif isinstance(node, list):
            for x in node:
                collect(x)

    collect(proj)
    print(f"[i] collected {len(used_ids)} existing ids (avoiding collisions)")

    dashboard = None
    for s in proj.get("FrontJson", []):
        if s.get("name") == "dashboard":
            dashboard = s
            break
    if dashboard is None:
        print("[err] 'dashboard' screen not found in FrontJson", file=sys.stderr)
        return 1

    # Replace the entire screen contents. Preserve the screen meta-fields.
    new_widgets = build_cockpit_widgets(used_ids)
    legacy_stubs = build_legacy_stubs(BACKUP, used_ids)
    # GUI Guider reverses the order when exporting setup_scr_dashboard.c
    # (first in JSON list -> last in code -> top z-layer). To keep
    # backgrounds/dividers below the digits we reverse the final list — the
    # script writes a visually natural order (bg first, then text), and the
    # JSON file gets the opposite order.
    dashboard["list"] = list(reversed(new_widgets + legacy_stubs))
    # While we're here, set the screen background to the Cockpit colour.
    scr_styles = dashboard.get("style", [])
    if scr_styles:
        m = scr_styles[0]
        m["bg_color"] = BG_0
        m["bg_grad_color"] = BG_0
        m["bg_opa"] = 255
        m["bg_grad_dir"] = "LV_GRAD_DIR_NONE"
        if "bg_img_src" in m:
            m["bg_img_src"] = ""
            m["bg_img_opa"] = 0

    # Application.screen[0] could be cleaned up too, but in this project file
    # Application.screen[0].widgets/list is empty and unused — leaving it.

    with open(PROJECT, "w", encoding="utf-8") as f:
        json.dump(proj, f, ensure_ascii=False, indent=1)
    # GUI Guider uses tabs for indentation, but indentation is not important
    # on reload — JSON is parsed regardless.

    print(f"[ok] dashboard rewritten: {len(new_widgets)} Cockpit widgets, "
          f"{len(legacy_stubs)} legacy stubs")
    print(f"[ok] {PROJECT}")
    print()
    print("next, in GUI Guider:")
    print("  1. File -> Open Project -> Super_VESC_Display.guiguider")
    print("  2. dashboard screen now shows the Cockpit; tweak visually if needed")
    print("  3. Generate Code -> rebuilds generated/setup_scr_dashboard.c")
    return 0


if __name__ == "__main__":
    sys.exit(main())
