#!/usr/bin/env python3
"""Convert the WHOLE dashboard_amber screen to the DSEG14 Classic 14-segment
font (labels + numbers — one segmented typeface everywhere).

Why DSEG14 and not DSEG7: DSEG7 has only digits/punctuation, so labels
(BATTERY, POWER, KM, V…) can't render in it. DSEG14 is the alphanumeric
14-segment ("starburst") sibling — it has A-Z, so the entire screen can be
segmented.

What it touches (keeps all three representations in sync):
  * Super_VESC_Display.guiguider — every label's font_family -> DSEG14Classic_Regular
    in both FrontJson (editor canvas) and Application.screen (codegen source);
    registers the ttf in ImportFonts. This is the SOURCE OF TRUTH: a GUI Guider
    "Generate Code" reproduces the DSEG14 references from here.
  * generated/setup_scr_dashboard_amber.c — swaps every font ref to DSEG14 at the
    same size (so the simulator/firmware render it without a Generate Code).
  * generated/gui_guider.h — LV_FONT_DECLARE for the DSEG14 sizes used.
  * generated/guider_fonts/fonts_list.mk — lists the DSEG14 .c for the simulator.

DSEG14 has no middle-dot (U+00B7): "·" is rewritten to "-" (M-TEMP, C-TEMP,
SPEED - KM/H).

Sizes must already be generated by regen_cockpit_fonts.py (digit subset for the
big numeric-only 50/64/200, full charset for the label sizes). Run that first.

Idempotent. Font subsets are regenerated by regen_cockpit_fonts.py; the firmware
CMake re-subsets into the build dir, the simulator needs a manual regen after any
GUI Guider "Generate Code" (same as Antonio/DSEG7).
"""
import json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GUI  = os.path.join(ROOT, "Super_VESC_Display.guiguider")
CSRC = os.path.join(ROOT, "generated", "setup_scr_dashboard_amber.c")
GH   = os.path.join(ROOT, "generated", "gui_guider.h")
FLMK = os.path.join(ROOT, "generated", "guider_fonts", "fonts_list.mk")

SCREEN = "dashboard_amber"
NEWFAM = "DSEG14Classic_Regular"
TTF_REF = "font\\DSEG14Classic-Regular.ttf"
OLD_FAMS = ["montserratMedium", "Antonio_Regular", "DSEG7Classic_Regular"]
GEN_SIZES = {11, 12, 16, 18, 20, 22, 24, 25, 26, 50, 64, 200}  # what regen made
MIDDOT, DASH = "·", "-"


def conv_styles(it):
    """Set the ACTIVE style entries' font_family to DSEG14; return sizes seen.
    Skip disable:true entries — GUI Guider never emits those to code, and their
    sizes (14/32/220 placeholders) have no generated DSEG14 font."""
    seen = set()
    for e in (it.get("style") or []):
        if e.get("disable") is True:
            continue
        if "font_family" in e or "font" in e:
            e["font_family"] = NEWFAM
        if e.get("font"):
            seen.add(e["font"])
    return seen


def walk(items, child_keys, seen):
    for it in items:
        if it.get("type") == "label":
            seen |= conv_styles(it)
            if it.get("text"):
                it["text"] = it["text"].replace(MIDDOT, DASH)
        for k in child_keys:
            ch = it.get(k)
            if ch:
                walk(ch, child_keys, seen)


def patch_guiguider():
    with open(GUI) as f:
        d = json.load(f)
    seen = set()
    for s in d.get("FrontJson", []):
        if s.get("name") == SCREEN:
            walk(s.get("list", []), ("list", "children"), seen)
    for s in d.get("Application", {}).get("screen", []):
        if s.get("name") == SCREEN:
            walk(s.get("widgets", []), ("widgets", "list", "children"), seen)
    d.setdefault("ImportFonts", {})[NEWFAM] = TTF_REF
    with open(GUI, "w") as f:
        json.dump(d, f, ensure_ascii=False, indent=1)
    missing = seen - GEN_SIZES
    print(f"[guiguider] dashboard_amber -> {NEWFAM}; sizes used: {sorted(seen)}")
    if missing:
        print(f"  [WARN] sizes with NO generated DSEG14 font: {sorted(missing)} "
              f"-> add to regen_cockpit_fonts.py JOBS")
    return seen


def patch_c():
    with open(CSRC) as f:
        src = f.read()
    n = 0
    for fam in OLD_FAMS:
        src, k = re.subn(rf"&lv_font_{fam}_(\d+)\b", r"&lv_font_DSEG14Classic_Regular_\1", src)
        n += k
    md = src.count(MIDDOT)
    src = src.replace(MIDDOT, DASH)
    with open(CSRC, "w") as f:
        f.write(src)
    print(f"[c] {n} font refs -> DSEG14, {md} middot -> dash")
    # sanity: no old amber font families remain
    leftover = [f for f in OLD_FAMS if f"&lv_font_{f}_" in src]
    if leftover:
        print(f"  [WARN] still references: {leftover}")


def patch_gui_guider_h():
    with open(GH) as f:
        gh = f.read()
    add = [s for s in sorted(GEN_SIZES)
           if f"lv_font_DSEG14Classic_Regular_{s})" not in gh]
    if not add:
        print("[gui_guider.h] DSEG14 declares already present")
        return
    block = "".join(f"LV_FONT_DECLARE(lv_font_DSEG14Classic_Regular_{s})\n" for s in add)
    # insert after the last existing LV_FONT_DECLARE line
    lines = gh.splitlines(keepends=True)
    last = max(i for i, ln in enumerate(lines) if ln.startswith("LV_FONT_DECLARE("))
    lines.insert(last + 1, block)
    with open(GH, "w") as f:
        f.write("".join(lines))
    print(f"[gui_guider.h] +{len(add)} DSEG14 declares")


def patch_fonts_list_mk():
    with open(FLMK) as f:
        mk = f.read()
    add = [f"lv_font_DSEG14Classic_Regular_{s}.c" for s in sorted(GEN_SIZES)
           if f"lv_font_DSEG14Classic_Regular_{s}.c" not in mk]
    if not add:
        print("[fonts_list.mk] DSEG14 already listed")
        return
    mk = mk.rstrip("\n") + " " + " ".join(add) + "\n"
    with open(FLMK, "w") as f:
        f.write(mk)
    print(f"[fonts_list.mk] +{len(add)} DSEG14 .c (simulator)")


if __name__ == "__main__":
    patch_guiguider()
    patch_c()
    patch_gui_guider_h()
    patch_fonts_list_mk()
    with open(GUI) as f:
        json.load(f)
    print("[ok] .guiguider valid JSON; DSEG14 conversion complete")
