/// Where the navigator's data comes from and how much space it takes.
///
/// The routing graph and the search index are generated by scripts/mapgen and
/// fetched over plain HTTP — in development that is a `python3 -m http.server`
/// in the `vtiles/` directory, which is why the address is a setting rather
/// than a constant. Files can also be imported straight off the phone, which
/// is the quickest path when the two machines are not on the same network.
library;

import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';

import '../i18n/strings.dart';
import '../nav/map_data.dart';
import '../nav/way_classes.dart';
import '../settings/nav_settings.dart';

class MapDataScreen extends StatefulWidget {
  const MapDataScreen({super.key});

  @override
  State<MapDataScreen> createState() => _MapDataScreenState();
}

class _MapDataScreenState extends State<MapDataScreen> {
  final _url = TextEditingController();
  ({int bytes, int files})? _tileStats;

  @override
  void initState() {
    super.initState();
    _url.text = NavSettings.instance.serverUrl;
    _refreshTiles();
  }

  @override
  void dispose() {
    _url.dispose();
    super.dispose();
  }

  Future<void> _refreshTiles() async {
    final stats = await MapData.instance.tiles?.stats();
    if (mounted) setState(() => _tileStats = stats);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(t(context, 'mapdata.title'))),
      body: ListenableBuilder(
        listenable: Listenable.merge(
            <Listenable>[MapData.instance, NavSettings.instance]),
        builder: (context, _) => ListView(
          padding: const EdgeInsets.all(16),
          children: <Widget>[
            _statusCard(context),
            _serverCard(context),
            _importCard(context),
            _tilesCard(context),
            _profileCard(context),
            if (MapData.instance.state != MapDataState.absent) _deleteCard(context),
          ],
        ),
      ),
    );
  }

  Widget _statusCard(BuildContext context) {
    final data = MapData.instance;
    final graph = data.graph;
    final theme = Theme.of(context);
    final children = <Widget>[];

    switch (data.state) {
      case MapDataState.ready:
        children.add(Text(
          tf(context, 'mapdata.status.ready', <String, Object?>{
            'nodes': graph?.nodeCount ?? 0,
            'edges': graph?.edgeCount ?? 0,
            'mb': ((data.graphFile?.existsSync() ?? false)
                    ? data.graphFile!.lengthSync() / (1 << 20)
                    : 0)
                .toStringAsFixed(1),
          }),
          style: theme.textTheme.titleMedium,
        ));
        children.add(const SizedBox(height: 4));
        children.add(Text(
          data.index == null
              ? t(context, 'mapdata.status.noplaces')
              : tf(context, 'mapdata.status.places',
                  <String, Object?>{'places': data.index!.length}),
          style: theme.textTheme.bodySmall,
        ));
      case MapDataState.downloading:
        children.add(Text(tf(context, 'mapdata.downloading', <String, Object?>{
          'file': data.progressFile ?? '',
          'pct': (data.progress * 100).round(),
        })));
        children.add(const SizedBox(height: 8));
        children.add(LinearProgressIndicator(
            value: data.progress > 0 ? data.progress : null));
      case MapDataState.loading:
        children.add(Text(t(context, 'mapdata.status.loading')));
        children.add(const SizedBox(height: 8));
        children.add(const LinearProgressIndicator());
      case MapDataState.error:
        children.add(Text(
          data.messageKey == null
              ? t(context, 'settings.mapdata.subtitle.error')
              : tf(context, data.messageKey!, data.messageArgs ?? const {}),
          style: TextStyle(color: theme.colorScheme.error),
        ));
      case MapDataState.absent:
        children.add(Text(t(context, 'mapdata.status.none')));
    }

    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
            crossAxisAlignment: CrossAxisAlignment.start, children: children),
      ),
    );
  }

  Widget _serverCard(BuildContext context) {
    final busy = MapData.instance.state == MapDataState.downloading ||
        MapData.instance.state == MapDataState.loading;
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            TextField(
              controller: _url,
              keyboardType: TextInputType.url,
              autocorrect: false,
              decoration: InputDecoration(
                labelText: t(context, 'mapdata.server'),
                hintText: t(context, 'mapdata.server.hint'),
                helperText: t(context, 'mapdata.server.help'),
                helperMaxLines: 3,
              ),
              onChanged: NavSettings.instance.setServerUrl,
            ),
            const SizedBox(height: 12),
            Align(
              alignment: Alignment.centerRight,
              child: FilledButton.icon(
                icon: const Icon(Icons.download),
                label: Text(t(context, 'mapdata.download')),
                onPressed: busy
                    ? null
                    : () => MapData.instance.downloadFrom(_url.text),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _importCard(BuildContext context) {
    return Card(
      child: Column(
        children: <Widget>[
          ListTile(
            leading: const Icon(Icons.file_open_outlined),
            title: Text(t(context, 'mapdata.import.graph')),
            onTap: () => _pick(MapData.instance.importGraph),
          ),
          ListTile(
            leading: const Icon(Icons.manage_search),
            title: Text(t(context, 'mapdata.import.index')),
            onTap: () => _pick(MapData.instance.importIndex),
          ),
        ],
      ),
    );
  }

  /// Picks a file by path, never by bytes: the graph is 17 MB and `withData`
  /// would haul all of it through the platform channel.
  Future<void> _pick(Future<void> Function(String path) then) async {
    final picked = await FilePicker.platform.pickFiles();
    final path = picked?.files.single.path;
    if (path != null) await then(path);
  }

  Widget _tilesCard(BuildContext context) {
    final stats = _tileStats;
    final settings = NavSettings.instance;
    return Card(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          ListTile(
            leading: const Icon(Icons.grid_view),
            title: Text(t(context, 'mapdata.tiles.title')),
            subtitle: Text(stats == null || stats.files == 0
                ? t(context, 'mapdata.tiles.empty')
                : tf(context, 'mapdata.tiles.size', <String, Object?>{
                    'mb': (stats.bytes / (1 << 20)).toStringAsFixed(1),
                    'n': stats.files,
                  })),
          ),
          ListTile(
            title: Text(t(context, 'mapdata.tiles.cap')),
            trailing: DropdownButton<int>(
              value: settings.tileCapMb,
              items: const <int>[100, 300, 1000]
                  .map((mb) =>
                      DropdownMenuItem<int>(value: mb, child: Text('$mb MB')))
                  .toList(),
              onChanged: (v) => v == null ? null : settings.setTileCapMb(v),
            ),
          ),
          ListTile(
            title: Text(t(context, 'mapdata.corridor.max')),
            trailing: DropdownButton<int>(
              value: settings.corridorMaxTiles,
              items: const <int>[100, 250, 600]
                  .map((n) =>
                      DropdownMenuItem<int>(value: n, child: Text('$n')))
                  .toList(),
              onChanged: (v) =>
                  v == null ? null : settings.setCorridorMaxTiles(v),
            ),
          ),
          Align(
            alignment: Alignment.centerRight,
            child: Padding(
              padding: const EdgeInsets.only(right: 8, bottom: 8),
              child: TextButton.icon(
                icon: const Icon(Icons.delete_outline, size: 18),
                label: Text(t(context, 'mapdata.tiles.clear')),
                onPressed: (stats?.files ?? 0) == 0
                    ? null
                    : () async {
                        if (await _confirm(context, 'mapdata.tiles.clear.confirm')) {
                          await MapData.instance.tiles?.clear();
                          await _refreshTiles();
                        }
                      },
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _profileCard(BuildContext context) {
    return Card(
      child: ListTile(
        leading: const Icon(Icons.route_outlined),
        title: Text(t(context, 'mapdata.profile.default')),
        trailing: DropdownButton<RideProfile>(
          value: NavSettings.instance.profile,
          items: RideProfile.values
              .map((p) => DropdownMenuItem<RideProfile>(
                  value: p, child: Text(t(context, p.i18nKey))))
              .toList(),
          onChanged: (p) =>
              p == null ? null : NavSettings.instance.setProfile(p),
        ),
      ),
    );
  }

  Widget _deleteCard(BuildContext context) {
    return Card(
      child: ListTile(
        leading: Icon(Icons.delete_forever,
            color: Theme.of(context).colorScheme.error),
        title: Text(t(context, 'mapdata.delete')),
        onTap: () async {
          if (await _confirm(context, 'mapdata.delete.confirm')) {
            await MapData.instance.deleteAll();
          }
        },
      ),
    );
  }

  Future<bool> _confirm(BuildContext context, String bodyKey) async {
    final ok = await showDialog<bool>(
      context: context,
      builder: (ctx) => AlertDialog(
        content: Text(t(ctx, bodyKey)),
        actions: <Widget>[
          TextButton(
              onPressed: () => Navigator.pop(ctx, false),
              child: Text(t(ctx, 'home.forget.cancel'))),
          FilledButton(
              onPressed: () => Navigator.pop(ctx, true),
              child: Text(t(ctx, 'home.forget.ok'))),
        ],
      ),
    );
    return ok ?? false;
  }
}
